import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import test from 'node:test'

const root = resolve(import.meta.dirname, '..')
const readJson = async path => JSON.parse(await readFile(resolve(root, path), 'utf8'))
const readJsonl = async path => (await readFile(resolve(root, path), 'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse)

test('DE405 route root-cause joined corpus and primary reconciliation are exact', async () => {
  const rows = await readJsonl('artifacts/de405-route-root-cause-joined.jsonl')
  const summary = await readJson('artifacts/de405-route-root-cause-summary.json')
  const clusters = await readJsonl('artifacts/de405-route-root-cause-clusters.jsonl')
  const sentinels = await readJsonl('artifacts/de405-route-root-cause-sentinels.jsonl')
  const manifest = await readJson('artifacts/de405-route-root-cause-artifact-manifest.json')
  const reconciliation = await readJson('artifacts/de405-route-root-cause-reconciliation.json')
  assert.equal(rows.length, 1701)
  assert.equal(new Set(rows.map(row => row.caseId)).size, 1701)
  assert.deepEqual(summary.primaryCounts, { accumulator_output_divergence: 513, final_assembly_divergence: 479, raw_leg_state_divergence: 709 })
  assert.equal(summary.routeExact, 1583)
  assert.equal(summary.baselineFinalExact, 1222)
  assert.equal(summary.chainLengthDifference, 118)
  assert.deepEqual(summary.originalEvaluatorAncestryCounts, { null: 1547, position_polynomial_ancestry: 93, velocity_derivative_ancestry: 61 })
  assert.equal(clusters.length, 4)
  assert.equal(sentinels.length, 20)
  assert.ok(clusters.every(cluster => cluster.counterexampleCaseId))
  assert.equal(sentinels.filter(sentinel => sentinel.kind === 'counterexample' && sentinel.membershipRuleMatches === false).length, 4)
  assert.equal(sentinels.filter(sentinel => sentinel.kind === 'boundary_or_extreme').length, 4)
  assert.ok(Object.keys(manifest.artifacts).length >= 12)
  assert.ok(Object.values(manifest.artifacts).every(artifact => artifact.path.startsWith('artifacts/') && !artifact.path.includes('/tmp/')))
  assert.equal(reconciliation.sources.routeEvents.missingAuthoritativeRows, 0)
  assert.equal(reconciliation.sources.projectEvents.missingAuthoritativeRows, 0)
  assert.equal(reconciliation.sources.routeSummary.declared.executionErrors, 0)
})

test('DE405 route candidates remain shadow-only and reconcile every case', async () => {
  const registry = await readJson('artifacts/de405-route-candidate-registry.json')
  const results = await readJson('artifacts/de405-route-candidate-shadow-results.json')
  const outcomes = await readJsonl('artifacts/de405-route-candidate-outcomes.jsonl')
  assert.equal(registry.productionActivation, 'forbidden')
  assert.equal(results.candidates.length, 4)
  assert.equal(outcomes.length, 4 * 1701)
  assert.ok(results.candidates.every(candidate => candidate.reconciliation))
  assert.ok(registry.candidates.every(candidate => candidate.clusters.length > 0))
  assert.ok(results.candidates.every(candidate => Object.values(candidate.outcomeCounts).reduce((sum, count) => sum + count, 0) === 1701))
  const type2 = results.candidates.find(candidate => candidate.candidateId === 'D405-CAND-TYPE2-OFFICIAL-ORDER')
  const accumulator = results.candidates.find(candidate => candidate.candidateId === 'D405-CAND-ACCUMULATOR-OBSERVED-ORDER')
  const finalAssembly = results.candidates.find(candidate => candidate.candidateId === 'D405-CAND-FINAL-ASSEMBLY-OBSERVED')
  const chain = results.candidates.find(candidate => candidate.candidateId === 'D405-CAND-CHAIN-ROUTE-EQUIVALENCE')
  assert.equal(type2.changedCases, 371)
  assert.equal(type2.counterfactualStateExactCases, 1583)
  assert.equal(type2.resolvedCases, 0)
  assert.equal(type2.regressions, 0)
  assert.deepEqual({ applicable: accumulator.applicableCases, changed: accumulator.changedCases, finalExact: accumulator.counterfactualStateExactCases, inputParity: accumulator.accumulatorInputParityAfter }, { applicable: 513, changed: 513, finalExact: 513, inputParity: 513 })
  assert.deepEqual({ applicable: finalAssembly.applicableCases, changed: finalAssembly.changedCases, finalExact: finalAssembly.counterfactualStateExactCases }, { applicable: 479, changed: 0, finalExact: 0 })
  assert.deepEqual({ applicable: chain.applicableCases, changed: chain.changedCases, finalExact: chain.counterfactualStateExactCases, routeExact: chain.exactRouteParityAfter }, { applicable: 118, changed: 118, finalExact: 118, routeExact: 118 })
})

test('DE405 route cross-tabs and combinations reconcile to the authoritative corpus', async () => {
  const tabs = await readJson('artifacts/de405-route-root-cause-cross-tabs.json')
  const combinations = await readJson('artifacts/de405-route-candidate-combinations.json')
  assert.ok(tabs.aggregateReconciliation.every(row => row.total === 1701))
  assert.ok(tabs.matrices.some(row => row.matrix === 'evaluator_ancestry_vs_primary'))
  assert.ok(tabs.matrices.some(row => row.matrix === 'evaluator_ancestry_vs_first_leg'))
  assert.equal(combinations.combinations.length, 5)
  assert.ok(combinations.combinations.every(row => row.inputCount === 1701 && row.regressions === 0))
  assert.ok(combinations.combinations.some(row => row.exclusionReason === 'no_case_satisfies_all_component_applicability_rules'))
})

test('DE405 wider replay records shadow parity without claiming production regression', async () => {
  const report = await readJson('artifacts/de405-route-wider-regression.json')
  assert.equal(report.scope, 'wider_type2_shadow_parity')
  assert.equal(report.sourceCorpus.rowCount, 150671)
  assert.equal(report.shadow.counts.shadowRows, 150671)
  assert.equal(report.shadow.counts.missingRows, 0)
  assert.equal(report.shadow.counts.executionErrors, 0)
  assert.equal(report.shadow.counts.targetRecordMismatch, 0)
  assert.equal(report.candidateInterpretation.productionRegressionStatus, 'not_established')
  assert.equal(report.sourceCorpus.comparisonScopes.previouslyExactProjectCspiceRows, null)
  assert.equal(report.sourceCorpus.comparisonScopes.projectRouteEventRows, null)
  assert.ok(report.sourceCorpus.uniqueSegmentInputs > 0)
  assert.ok(report.sourceCorpus.uniqueSegmentRecordInputs > 0)
  assert.deepEqual(report.sourceCorpus.observers, [399])
  assert.ok(report.sourceCorpus.coverageBoundaryRows.length > 0)
})
