import test from 'node:test'
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'

const readJson = async path => JSON.parse(await readFile(path, 'utf8'))
const sha256 = async path => createHash('sha256').update(await readFile(path)).digest('hex')

test('Strategy C boundary evidence has a current, fail-closed contract', async () => {
  const comparison = await readJson('artifacts/de405-strategy-c-boundary-comparison.json')
  const inventory = await readJson('artifacts/de405-strategy-c-boundary-inventory.json')
  const support = await readJson('artifacts/de405-strategy-c-support-contract.json')
  const centerChain = await readJson('artifacts/de405-strategy-c-center-chain-comparison.json')
  const route = await readJson('artifacts/de405-strategy-c-route-comparison.json')
  const completion = await readJson('artifacts/de405-strategy-c-completion-audit.json')
  const canonicalRouteVariant = await readJson('artifacts/de405-strategy-c-canonical-route-variant-evidence.json')
  const priorBaselineFidelity = await readJson('artifacts/de405-type2-strategy-baseline-fidelity.json')
  assert.equal(comparison.schemaVersion, 1)
  assert.equal(comparison.recordType, 'de405_strategy_c_boundary_comparison')
  assert.equal(comparison.verdict, 'partial_strategy_c_support_contract_unproven')
  assert.equal(comparison.repositoryBaseline.branch, 'main')
  assert.equal(comparison.repositoryBaseline.head, comparison.repositoryBaseline.originMain)
  assert.equal(comparison.input.rowCount, 150671)
  assert.deepEqual(comparison.currentCorpus, {
    sourceRows: 150671,
    canonicalRows: 150671,
    integrationRows: 150671,
    shadowRows: 150671,
    identityErrors: 0,
    integrationOutputMismatches: 0,
    integrationRouteMismatches: 0,
    baselineExact: 79820,
    candidateExact: 95882,
    candidateChanged: 18381,
    candidateResolved: 16062,
    candidateRegressed: 0,
    executionErrors: 0,
    firstDivergence: comparison.currentCorpus.firstDivergence
  })
  assert.equal(comparison.currentCorpus.baselineExact, 79820)
  assert.equal(comparison.currentCorpus.candidateExact, 95882)
  assert.equal(comparison.priorArtifactReconciliation.reconciliation, 'matched')
  assert.equal(comparison.integrationBoundary.evaluatorStateComparison.comparisons, 148970)
  assert.equal(comparison.integrationBoundary.evaluatorStateComparison.mismatches, 0)
  assert.equal(comparison.gates.fullCanonicalCenterChainComparison, false)
  assert.equal(comparison.gates.canonicalCenterChainNeutrality, true)
  assert.equal(comparison.gates.shadowComparableRouteCandidateExact, true)
  assert.equal(comparison.gates.supportMatrixComplete, false)
  assert.equal(comparison.gates.supportFixtureContract, true)
  assert.equal(comparison.gates.tolerancePrecisionPassFailUnchanged, true)
  assert.equal(comparison.gates.deterministicTwoRunByteIdentity, true)
  assert.equal(comparison.integrationBoundary.centerChain.observed, true)
  assert.equal(comparison.integrationBoundary.centerChain.candidateShadowMismatches, 54789)
  assert.equal(comparison.gates.fullCanonicalCenterChainComparison, false)
  assert.equal(comparison.protectedProduction.productionActivation, false)
  assert.equal(comparison.sourceIdentities.canonicalSource.sha256, await sha256('tools/de405-cspice-runner/src/de405_canonical_v2.c'))
  assert.equal(comparison.sourceIdentities.integrationAdapter.sha256, await sha256('tools/de405-type2-strategy-c-integration/src/de405_type2_strategy_c_integration.c'))
  assert.equal(comparison.evidenceArtifacts.centerChainComparison.sha256, await sha256('artifacts/de405-strategy-c-center-chain-comparison.json'))
  assert.equal(comparison.evidenceArtifacts.routeComparison.sha256, await sha256('artifacts/de405-strategy-c-route-comparison.json'))
  assert.equal(comparison.evidenceArtifacts.supportAudit.sha256, await sha256('artifacts/de405-strategy-c-support-audit.json'))
  assert.equal(comparison.canonicalBoundary.route.at(-1), 'J2000/NONE km and km/s')
  assert.equal(inventory.callGraph.publicEntry, 'main -> evaluate_batch')
  assert.equal(inventory.callGraph.type2Evaluator.includes('chbint_c'), true)
  assert.equal(inventory.callGraph.centerChain.includes('spkez_c'), true)
  assert.deepEqual(inventory.sentinelGates.type2Trace154, { command: 'npm run test:de405:artifacts', expected: 154, observed: 154, exact: 154, status: 'passed' })
  assert.deepEqual(inventory.sentinelGates.selectionAmbiguous1701, { command: 'npm run test:de405:artifacts', expected: 1701, observed: 1701, executionErrors: 0, status: 'passed' })
  assert.equal(inventory.integrationBoundary.substitutionSeam, 'evaluate_record -> chbint_c only')
  assert.equal(support.recordType, 'de405_strategy_c_support_contract_audit')
  assert.equal(support.allContractEqual, true)
  assert.equal(support.repeatabilityEqual, true)
  assert.equal(support.executionOrderInvariant, true)
  assert.equal(support.parallelExecutionInvariant, true)
  assert.equal(support.supportClassification.noNewSupportDeclaration, true)
  assert.equal(centerChain.recordType, 'de405_strategy_c_center_chain_comparison')
  assert.equal(centerChain.counts.rows, 150671)
  assert.equal(centerChain.counts.identityErrors, 0)
  assert.equal(centerChain.counts.integrationCandidateMismatches, 54789)
  assert.equal(centerChain.counts.matrix.integrationEqualsCanonical, 150671)
  assert.equal(centerChain.counts.matrix.integrationEqualsCanonicalWhenShadowCandidateDiffers, 54789)
  assert.equal(centerChain.counts.integrationErrors, 0)
  assert.equal(route.recordType, 'de405_strategy_c_route_comparison')
  assert.equal(route.counts.rows, 150671)
  assert.equal(route.counts.identityErrors, 0)
  assert.equal(route.counts.routeIdentityExact, 95882)
  assert.equal(route.counts.routeIdentityMismatch, 54789)
  assert.equal(route.counts.evaluatorStateMismatch, 0)
  assert.equal(route.counts.candidateRouteComparableRows, 95882)
  assert.equal(route.counts.candidateRouteComparableMismatchRows, 0)
  assert.equal(completion.schemaVersion, 1)
  assert.equal(completion.recordType, 'de405_strategy_c_completion_audit')
  assert.equal(completion.proposalEligibility, 'not_eligible')
  assert.equal(completion.proposalNotGenerated, true)
  assert.equal(completion.repositoryBaseline.parity, true)
  assert.equal(completion.baselineReconciliation.requestedBaselineExactness, 150671)
  assert.equal(completion.baselineReconciliation.corpusIdentityRows, 150671)
  assert.equal(completion.baselineReconciliation.preservedLegacyBaselineExact, 79820)
  assert.equal(completion.baselineReconciliation.canonicalRouteVariantBaselineExact, 133392)
  assert.equal(completion.baselineReconciliation.priorReferenceBaselineExact, priorBaselineFidelity.baselineReferenceExact)
  assert.equal(completion.baselineReconciliation.status, 'requested_150671_baseline_numeric_exactness_not_reconciled')
  assert.equal(completion.requirements.find(item => item.id === 'full_shadow_candidate_all_rows').status, 'not_proved')
  assert.equal(completion.requirements.find(item => item.id === 'baseline_exactness_150671').status, 'not_proved')
  assert.equal(completion.requirements.find(item => item.id === 'baseline_normal_case_output_route_unchanged').status, 'not_proved')
  assert.equal(completion.requirements.find(item => item.id === 'canonical_route_variant_full_corpus').status, 'proved')
  assert.equal(completion.requirements.find(item => item.id === 'route_comparable_shadow_candidate').status, 'proved')
  assert.equal(completion.evidenceArtifacts['artifacts/de405-strategy-c-route-comparison.json'].sha256, await sha256('artifacts/de405-strategy-c-route-comparison.json'))
  assert.equal(completion.evidenceArtifacts['artifacts/de405-strategy-c-boundary-comparison.md'].sha256, await sha256('artifacts/de405-strategy-c-boundary-comparison.md'))
  assert.equal(completion.evidenceArtifacts['artifacts/de405-strategy-c-canonical-route-variant-evidence.json'].sha256, await sha256('artifacts/de405-strategy-c-canonical-route-variant-evidence.json'))
  assert.equal(completion.evidenceArtifacts['artifacts/de405-strategy-c-canonical-route-variant-evidence.md'].sha256, await sha256('artifacts/de405-strategy-c-canonical-route-variant-evidence.md'))
  assert.equal(completion.evidenceArtifacts['artifacts/de405-strategy-c-canonical-route-full-audit.json'].sha256, await sha256('artifacts/de405-strategy-c-canonical-route-full-audit.json'))
  assert.equal(canonicalRouteVariant.schemaVersion, 1)
  assert.equal(canonicalRouteVariant.recordType, 'de405_strategy_c_canonical_route_variant_evidence')
  assert.equal(canonicalRouteVariant.legacyShadow.counts.rows, 150671)
  assert.equal(canonicalRouteVariant.legacyShadow.counts.changed, 18381)
  assert.equal(canonicalRouteVariant.legacyShadow.counts.resolved, 16062)
  assert.equal(canonicalRouteVariant.fullNumeric.counts.candidateExact, 150671)
  assert.equal(canonicalRouteVariant.fullNumeric.counts.candidateRegressed, 0)
  assert.equal(canonicalRouteVariant.routeSentinel.counts.routeIdentityMismatch, 0)
  assert.equal(canonicalRouteVariant.routeSentinel.counts.evaluatorStateMismatch, 0)
  assert.equal(canonicalRouteVariant.fullRouteStatus, 'proved')
  assert.equal(canonicalRouteVariant.gates.fullRouteIdentityExact, true)
})
