import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { materializeAcquisitionFeasibility, SCHEMA } from '../scripts/materialize-ziwei-clean-rule-corpus-source-acquisition-feasibility-v0.mjs'
const root = process.cwd(); const materializer = join(root, 'scripts/materialize-ziwei-clean-rule-corpus-source-acquisition-feasibility-v0.mjs'); const checker = join(root, 'scripts/check-ziwei-clean-rule-corpus-source-acquisition-feasibility-v0.mjs'); const negative = join(root, 'scripts/check-ziwei-clean-rule-corpus-source-acquisition-feasibility-negative-v0.mjs')
test('acquisition feasibility mechanically selects blocked ledger candidates and materializes byte-identically', async () => { const dir = await mkdtemp(join(tmpdir(), 'ziwei-acquisition-feasibility-')); try { const a = join(dir, 'a.json'); const b = join(dir, 'b.json'); assert.equal(spawnSync(process.execPath, [materializer, a], { cwd: root, encoding: 'utf8' }).status, 0); assert.equal(spawnSync(process.execPath, [materializer, b], { cwd: root, encoding: 'utf8' }).status, 0); assert.deepEqual(await readFile(a), await readFile(b)); const checked = spawnSync(process.execPath, [checker, a], { cwd: root, encoding: 'utf8' }); assert.equal(checked.status, 0, checked.stdout + checked.stderr); const result = JSON.parse(checked.stdout); assert.equal(result.pass, true); assert.deepEqual(result.selectedAccessBlocked, ['ctext-ziwei-page-res-979714', 'google-books-2000-dingwen-ming007', 'ndltd-097cgu05121028-exchange-rate-study']); assert.equal(result.alternativeSeedAdmissibleCount, 0) } finally { await rm(dir, { recursive: true, force: true }) } })
test('acquisition feasibility keeps downstream boundary closed', async () => { const artifact = await materializeAcquisitionFeasibility(); assert.equal(artifact.schemaVersion, SCHEMA); assert.equal(artifact.downstreamBoundaries.stableClaimCount, 0); assert.equal(artifact.downstreamBoundaries.grounding, 'blocked'); assert.equal(artifact.alternativeSeedAssessment.admissibleCount, 0); assert.equal(artifact.sourceVerdicts['google-books-2000-dingwen-ming007'].bytes, false); assert.equal(artifact.sourceVerdicts['google-books-2000-dingwen-ming007'].hash, false) })
test('negative fixture detects acquisition and promotion shortcuts', () => { const result = spawnSync(process.execPath, [negative], { cwd: root, encoding: 'utf8' }); assert.equal(result.status, 0, result.stdout + result.stderr); const parsed = JSON.parse(result.stdout); assert.equal(parsed.pass, true); assert.equal(parsed.caseCount, 17); assert.equal(parsed.findings.length, 17) })
