import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile, mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { materializeArchiveScanSourceWitness } from '../scripts/materialize-ziwei-archive-scan-source-witness-admission-v0.mjs'
const root=process.cwd(); const materializer=join(root,'scripts/materialize-ziwei-archive-scan-source-witness-admission-v0.mjs'); const checker=join(root,'scripts/check-ziwei-archive-scan-source-witness-admission-v0.mjs'); const negative=join(root,'scripts/check-ziwei-archive-scan-source-witness-admission-negative-v0.mjs'); const pdf='/Users/softie/Downloads/命-南北山人_紫微斗数全书.pdf'
test('archive witness materializes byte-identically and re-verifies local PDF',async()=>{const dir=await mkdtemp(join(tmpdir(),'ziwei-archive-admission-'));try{const a=join(dir,'a.json'),b=join(dir,'b.json');assert.equal(spawnSync(process.execPath,[materializer,a],{cwd:root,encoding:'utf8'}).status,0);assert.equal(spawnSync(process.execPath,[materializer,b],{cwd:root,encoding:'utf8'}).status,0);assert.deepEqual(await readFile(a),await readFile(b));const c=spawnSync(process.execPath,[checker,a,pdf],{cwd:root,encoding:'utf8'});assert.equal(c.status,0,c.stdout+c.stderr);assert.equal(JSON.parse(c.stdout).pdfReverified,true)}finally{await rm(dir,{recursive:true,force:true})}})
test('archive witness keeps claims, rights, and activation closed',async()=>{const a=await materializeArchiveScanSourceWitness();assert.equal(a.verdictToken,'source_witness_admissible_with_limits');assert.equal(a.digitalWitness.pdfPageCount,219);assert.equal(a.identityLayers.bibliographicEditionIdentity.status,'partial');assert.equal(a.identityLayers.rightsAccessStatus.status,'rights_unresolved');assert.equal(a.downstreamBoundaries.stableClaimCount,0);assert.equal(a.downstreamBoundaries.grounding,'blocked');assert.equal(a.seedCandidates.every(x=>x.extracted===false),true)})
test('negative fixture detects admission shortcuts',()=>{const r=spawnSync(process.execPath,[negative],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);const x=JSON.parse(r.stdout);assert.equal(x.pass,true);assert.equal(x.caseCount,17);assert.equal(x.findings.length,17)})
