const freezeFields = (fields) => Object.freeze(fields)

// This is the Google backup export contract. New columns must be reviewed and
// added explicitly; the materializer must never fall back to a wildcard select.
export const GOOGLE_BACKUP_FIELD_MANIFEST = Object.freeze({
  reservations: freezeFields([
    'id',
    'reservation_date',
    'branch',
    'room',
    'customer_name',
    'start_at',
    'duration_minutes',
    'end_at',
    'warning_offset_minutes',
    'tags',
    'notes_text',
    'created_at',
    'updated_at',
    'google_event_id',
    'owner_key',
    'regular_phone_last4',
    'regular_id',
  ]),
  work_events: freezeFields([
    'id',
    'reservation_id',
    'event_type',
    'scheduled_at',
    'status',
    'tags_snapshot',
    'memo_snapshot',
    'created_at',
    'updated_at',
  ]),
  scheduler_work_logs: freezeFields([
    'id',
    'owner_key',
    'week_start_date',
    'date',
    'start_time',
    'end_time',
    'duration_minutes',
    'branch',
    'room',
    'synced_at',
    'created_at',
    'updated_at',
  ]),
  saju_profiles: freezeFields([
    'id',
    'local_key',
    'name',
    'birth_date',
    'birth_time',
    'gender',
    'is_lunar',
    'is_leap_month',
    'timezone',
    'created_at',
    'updated_at',
    'user_id',
  ]),
  saju_natal_snapshots: freezeFields([
    'id',
    'profile_id',
    'year_stem',
    'year_branch',
    'month_stem',
    'month_branch',
    'day_stem',
    'day_branch',
    'hour_stem',
    'hour_branch',
    'day_master',
    'natal_data',
    'created_at',
    'updated_at',
  ]),
  saju_daily_snapshots: freezeFields([
    'id',
    'profile_id',
    'target_date',
    'daily_stem',
    'daily_branch',
    'computed_data',
    'created_at',
    'updated_at',
  ]),
  saju_fortune_reports: freezeFields([
    'id',
    'profile_id',
    'daily_snapshot_id',
    'report_date',
    'report_version',
    'model_name',
    'headline',
    'summary',
    'report_content',
    'generated_at',
    'created_at',
    'updated_at',
  ]),
  push_subscriptions: freezeFields([
    'id',
    'device_id',
    'endpoint',
    'endpoint_hash',
    'subscription',
    'user_agent',
    'platform',
    'notification_types',
    'active',
    'last_seen_at',
    'last_test_sent_at',
    'last_error_at',
    'last_error_message',
    'created_at',
    'updated_at',
    'notifications_enabled',
    'work_time_enabled',
    'work_time_start_hour',
    'work_time_end_hour',
    'work_time_selected_date',
    'owner_key',
  ]),
})

export const GOOGLE_BACKUP_TABLES = Object.freeze(Object.keys(GOOGLE_BACKUP_FIELD_MANIFEST))

export function getGoogleBackupSelectFields(tableName) {
  const fields = GOOGLE_BACKUP_FIELD_MANIFEST[tableName]
  if (!fields) {
    throw new Error(`Missing Google backup field manifest for ${tableName}`)
  }
  return fields.join(',')
}
