import { createHash } from 'node:crypto'
import { ASTROLOGY_INTERPRETATION_HANDOFF_SCHEMA, ASTROLOGY_INTERPRETATION_HANDOFF_VERSION, HANDOFF_ACTIVATION } from './astrologyInterpretationHandoff.js'
import { ASTROLOGY_INTERPRETATION_READ_PROTOCOL_SCHEMA, ASTROLOGY_INTERPRETATION_READ_PROTOCOL_VERSION, astrologyInterpretationReadProtocolContentSha256 } from './astrologyInterpretationReadProtocol.js'

export const ASTROLOGY_INTERPRETATION_CONFORMANCE_SCHEMA = 'astrology-interpretation-conformance-v1'
export const ASTROLOGY_INTERPRETATION_CONFORMANCE_VERSION = '1.0.0'
export const CONFORMANCE_CANDIDATE_SCHEMA = 'astrology-interpretation-downstream-candidate-v1'
export const CONFORMANCE_CANDIDATE_VERSION = '1.0.0'
export const CONFORMANCE_VIOLATIONS = Object.freeze([
  'bundle_protocol_schema_version_mismatch', 'bundle_protocol_hash_mismatch', 'candidate_schema_version_mismatch', 'candidate_content_hash_mismatch',
  'claim_missing', 'claim_deleted', 'claim_merged', 'claim_mutated', 'claim_created', 'claim_source_refs_unresolvable', 'provenance_disconnected',
  'epistemic_class_mixed', 'graph_relation_semantics_transformed', 'calculation_strength_as_meaning_weight', 'pre_experience_dominance_decision',
  'unsupported_psychology_assertion', 'activation_delivery_production_promoted', 'calculation_contamination', 'prompt_llm_api_trace',
  'candidate_contract_violation',
])
export const CONFORMANCE_REQUIREMENTS = Object.freeze([
  'identity_and_content_hashes', 'claim_reference_fidelity', 'source_refs_and_provenance', 'epistemic_boundary', 'structural_graph_relations_only',
  'no_strength_to_meaning_conversion', 'no_pre_experience_precedence', 'no_unsupported_psychology_or_destiny', 'activation_delivery_production_boundary', 'no_prompt_llm_api_trace',
].map((requirement, order) => Object.freeze({ order: order + 1, requirement, onFailure: 'stop_and_block' })))
const HASH = /^[a-f0-9]{64}$/
const isObject = value => value && typeof value === 'object' && !Array.isArray(value)
const ordered = value => Array.isArray(value) ? value.map(ordered) : (!value || typeof value !== 'object' ? value : Object.fromEntries(Object.keys(value).sort().map(key => [key, ordered(value[key])])))
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex')
const contentHash = value => { const copy = structuredClone(value); delete copy.candidateContentSha256; return sha256(`${JSON.stringify(ordered(copy))}\n`) }
const canonical = value => `${JSON.stringify(ordered(value))}\n`
const add = (violations, code, location, claimRefs = [], sourceRefs = []) => { if (!violations.some(item => item.code === code && item.location === location)) violations.push({ code, location, claimRefs: [...new Set(claimRefs)].sort(), sourceRefs: [...new Set(sourceRefs)].sort() }) }
const walk = (value, path = '', result = []) => { if (!value || typeof value !== 'object') return result; if (Object.hasOwn(value, 'claimType') && Object.hasOwn(value, 'value')) result.push({ path: path || '/', claim: value }); for (const [key, child] of Object.entries(value)) walk(child, `${path}/${key}`, result); return result }
const forbiddenKeys = new Set(['theme', 'narrative', 'personality', 'psychology', 'strength', 'weakness', 'wound', 'desire', 'risk', 'destiny', 'meaningWeight', 'meaning_weight', 'priority', 'ranking', 'rank', 'winner', 'dominance', 'conflict', 'balance', 'prompt', 'template', 'systemMessage', 'llm', 'api'])
const findForbidden = (value, path = '', result = []) => { if (!value || typeof value !== 'object') return result; for (const [key, child] of Object.entries(value)) { if (forbiddenKeys.has(key)) result.push(`${path}/${key}`); findForbidden(child, `${path}/${key}`, result) } return result }

export const canonicalAstrologyInterpretationConformanceJson = canonical
export const astrologyInterpretationCandidateContentSha256 = contentHash
export const astrologyInterpretationConformanceContentSha256 = value => { const copy = structuredClone(value); delete copy.conformanceContentSha256; return sha256(canonical(copy)) }

export function evaluateAstrologyInterpretationConformance({ handoff, protocol, graph, candidate } = {}) {
  const violations = []; const checks = []; const check = (requirement, ok, code, location = '/') => { checks.push({ requirement, status: ok ? 'passed' : 'failed', violationCodes: ok ? [] : [code] }); if (!ok) add(violations, code, location) }
  const bundle = handoff?.bundle || handoff; const bundleHash = bundle?.bundleContentSha256; const protocolHash = protocol?.protocolContentSha256
  check('identity_and_content_hashes', bundle?.schemaVersion === ASTROLOGY_INTERPRETATION_HANDOFF_SCHEMA && bundle?.handoffVersion === ASTROLOGY_INTERPRETATION_HANDOFF_VERSION && protocol?.schemaVersion === ASTROLOGY_INTERPRETATION_READ_PROTOCOL_SCHEMA && protocol?.protocolVersion === ASTROLOGY_INTERPRETATION_READ_PROTOCOL_VERSION && protocol?.protocolStatus === 'complete', 'bundle_protocol_schema_version_mismatch')
  check('identity_and_content_hashes', HASH.test(bundleHash || '') && HASH.test(protocolHash || '') && protocol?.input?.handoffContentSha256 === bundleHash && candidate?.input?.handoffSchemaVersion === bundle?.schemaVersion && candidate?.input?.handoffVersion === bundle?.handoffVersion && candidate?.input?.protocolSchemaVersion === protocol?.schemaVersion && candidate?.input?.protocolVersion === protocol?.protocolVersion && candidate?.input?.handoffContentSha256 === bundleHash && candidate?.input?.protocolContentSha256 === protocolHash, 'bundle_protocol_hash_mismatch', '/input')
  check('identity_and_content_hashes', candidate?.schemaVersion === CONFORMANCE_CANDIDATE_SCHEMA && candidate?.candidateVersion === CONFORMANCE_CANDIDATE_VERSION, 'candidate_schema_version_mismatch')
  check('candidate_content_hash', HASH.test(candidate?.candidateContentSha256 || '') && contentHash(candidate) === candidate.candidateContentSha256, 'candidate_content_hash_mismatch')
  const graphNodes = graph?.nodes || []
  const pathKey = path => path.replace(/^\/+/, '').replaceAll('/', '.')
  const nodes = (protocol?.claimSourceTrace || []).map(item => { const graphNode = graphNodes.find(node => pathKey(node.claimPath) === item.claimPath); return { claimPath: item.claimPath, claimType: graphNode?.claimType || null, value: graphNode?.value, sourceRefs: item.sourceRefs, epistemic: item.epistemic } })
  const refs = Array.isArray(candidate?.claims) ? candidate.claims : []; const byPath = new Map(nodes.map(item => [item.claimPath, item])); const seen = new Set()
  for (const [index, ref] of refs.entries()) { const location = `/claims/${index}`; if (!isObject(ref) || typeof ref.claimPath !== 'string') { add(violations, 'candidate_contract_violation', location); continue } if (seen.has(ref.claimPath)) add(violations, 'claim_merged', location, [ref.claimPath]); seen.add(ref.claimPath); const source = byPath.get(ref.claimPath); if (!source) { add(violations, 'claim_created', location, [ref.claimPath]); continue } if (JSON.stringify(ref.sourceRefs) !== JSON.stringify(source.sourceRefs) || ref.epistemic !== source.epistemic || ref.claimType !== source.claimType || JSON.stringify(ref.value) !== JSON.stringify(source.value)) add(violations, 'claim_mutated', location, [ref.claimPath], ref.sourceRefs); if (!Array.isArray(ref.sourceRefs) || ref.sourceRefs.some(sourceRef => !source.sourceRefs.includes(sourceRef))) add(violations, 'claim_source_refs_unresolvable', location, [ref.claimPath], ref.sourceRefs) }
  if (candidate?.coverage?.declaration !== 'all_upstream_claims') add(violations, 'claim_missing', '/coverage/declaration')
  for (const node of nodes) if (!seen.has(node.claimPath)) add(violations, 'claim_missing', '/claims', [node.claimPath], node.sourceRefs)
  check('claim_reference_fidelity', violations.every(item => !['claim_missing', 'claim_deleted', 'claim_merged', 'claim_mutated', 'claim_created'].includes(item.code)), 'claim_mutated', '/claims')
  check('source_refs_and_provenance', refs.length > 0 && refs.every(ref => Array.isArray(ref.sourceRefs) && ref.sourceRefs.length > 0), 'provenance_disconnected', '/claims')
  const usages = Array.isArray(candidate?.assertions) ? candidate.assertions : []
  for (const [index, assertion] of usages.entries()) { const location = `/assertions/${index}`; const kind = assertion?.kind; if (!['claim_reference', 'structural_relation_reference', 'epistemic_boundary', 'status_reference'].includes(kind)) add(violations, 'candidate_contract_violation', location); if (['support', 'conflict', 'dominance', 'winner', 'priority', 'meaning', 'meaning_weight', 'ranking'].includes(assertion?.relation)) add(violations, 'graph_relation_semantics_transformed', location, assertion.claimRefs, assertion.sourceRefs); if (['meaning_weight', 'priority', 'ranking', 'strength_as_importance', 'orb_as_life_importance', 'phase_as_life_importance', 'rule_as_life_importance'].includes(assertion?.interpretation)) add(violations, 'calculation_strength_as_meaning_weight', location, assertion.claimRefs, assertion.sourceRefs); if (['dominance_before_experience', 'winner_before_experience', 'pre_experience_precedence', 'cancellation_before_experience'].includes(assertion?.decision)) add(violations, 'pre_experience_dominance_decision', location, assertion.claimRefs, assertion.sourceRefs); if (['psychology', 'personality', 'destiny', 'unsupported_natural_language'].includes(assertion?.assertionType)) add(violations, 'unsupported_psychology_assertion', location, assertion.claimRefs, assertion.sourceRefs); if (assertion?.epistemicClass && assertion.claimRefs?.some(ref => byPath.get(ref)?.epistemic !== assertion.epistemicClass)) add(violations, 'epistemic_class_mixed', location, assertion.claimRefs, assertion.sourceRefs) }
  const graphRelations = new Set(bundle?.relationVocabulary || []); for (const [index, assertion] of usages.entries()) if (assertion?.kind === 'structural_relation_reference' && (!graphRelations.has(assertion.relation) || assertion.semanticUse !== 'structural_co_occurrence_only')) add(violations, 'graph_relation_semantics_transformed', `/assertions/${index}`, assertion.claimRefs, assertion.sourceRefs)
  if (JSON.stringify(candidate?.activation) !== JSON.stringify(HANDOFF_ACTIVATION)) add(violations, 'activation_delivery_production_promoted', '/activation')
  if (candidate?.deliveryStatus !== 'blocked') add(violations, 'activation_delivery_production_promoted', '/deliveryStatus')
  for (const location of findForbidden(candidate)) { const code = /prompt|template|systemMessage|llm|api/.test(location) ? 'prompt_llm_api_trace' : /meaning|priority|ranking|strength|winner|dominance|conflict|balance/.test(location) ? 'calculation_strength_as_meaning_weight' : 'unsupported_psychology_assertion'; add(violations, code, location) }
  const serialized = JSON.stringify(candidate || '').toLowerCase(); if (/simulation|placidus|frozen.?speed|legacy.?prep|unverified.?provider/.test(serialized)) add(violations, 'calculation_contamination', '/candidate')
  const pass = violations.length === 0; const result = { schemaVersion: ASTROLOGY_INTERPRETATION_CONFORMANCE_SCHEMA, conformanceVersion: ASTROLOGY_INTERPRETATION_CONFORMANCE_VERSION, verdict: pass ? 'conformant' : 'non_conformant', pass, input: { handoffSchemaVersion: bundle?.schemaVersion || null, handoffVersion: bundle?.handoffVersion || null, handoffContentSha256: bundleHash || null, protocolSchemaVersion: protocol?.schemaVersion || null, protocolVersion: protocol?.protocolVersion || null, protocolContentSha256: protocolHash || null, candidateSchemaVersion: candidate?.schemaVersion || null, candidateVersion: candidate?.candidateVersion || null, candidateContentSha256: candidate?.candidateContentSha256 || null }, requirements: CONFORMANCE_REQUIREMENTS, checks, violations: violations.sort((a, b) => `${a.code}${a.location}`.localeCompare(`${b.code}${b.location}`)), activation: { ...HANDOFF_ACTIVATION }, decisions: { localResearch: 'eligible_for_local_interpretation_research', userDelivery: 'blocked', productionActivation: 'blocked', humanReview: 'required' }, interpretationBoundary: { noScoring: true, noMeaningJudgment: true, noNaturalLanguageInference: true, noLlmCall: true, noActivation: true } }
  return { ...result, conformanceContentSha256: astrologyInterpretationConformanceContentSha256(result) }
}
