#include <inttypes.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SpiceUsr.h"

typedef struct { SpiceDouble dc[2], init, intlen; SpiceInt ic[6], rsize, n, degree, begin, end; char id[256]; int valid; } Segment;
static void die(const char *m) { fprintf(stderr, "%s\n", m); exit(1); }
static uint64_t dbits(double x) { uint64_t b; memcpy(&b, &x, 8); return b; }
static uint64_t ordered(double x) { uint64_t b=dbits(x); return (b>>63) ? ~b+1 : b|UINT64_C(0x8000000000000000); }
static int exact_int(double x, SpiceInt *out) { if (!isfinite(x)||trunc(x)!=x||x<1||x>2147483647.0) return 0; *out=(SpiceInt)x; return (double)*out==x; }
static int field(const char *line,const char *key,const char **p) { char n[128]; int k=snprintf(n,sizeof n,"\"%s\":",key); const char *q=k>0?strstr(line,n):NULL; if(!q)return 0;*p=q+k;return 1; }
static int strfield(const char *line,const char *key,char *out,size_t cap) { const char*p;if(!field(line,key,&p)||*p++!='\"')return 0;const char*e=strchr(p,'\"');if(!e||(size_t)(e-p)>=cap)return 0;memcpy(out,p,(size_t)(e-p));out[e-p]=0;return 1; }
static int intfield(const char *line,const char *key,SpiceInt *out) { const char*p;char*e;double x;if(!field(line,key,&p))return 0;x=strtod(p,&e);if(e==p||trunc(x)!=x||x<INT32_MIN||x>INT32_MAX)return 0;*out=(SpiceInt)x;return 1; }
static int numfield(const char *line,const char *key,double *out) { const char*p;char*e;if(!field(line,key,&p))return 0;*out=strtod(p,&e);return e!=p&&isfinite(*out); }
static int hexfield(const char*line,const char*key,uint64_t*out){char b[32],*e;unsigned long long v;if(!strfield(line,key,b,sizeof b)||strncmp(b,"0x",2))return 0;v=strtoull(b+2,&e,16);if(*e)return 0;*out=v;return 1;}
static void jsons(FILE*f,const char*s){fputc('\"',f);for(;*s;s++){if(*s=='\"'||*s=='\\')fputc('\\',f);fputc(*s,f);}fputc('\"',f);}
static int load(SpiceInt h, Segment *a, int cap) { SpiceDouble sum[5],dir[4]; SpiceBoolean found=SPICEFALSE;int n=0;dafbfs_c(h);while(1){daffna_c(&found);if(failed_c())die("DAF traversal failed");if(!found)break;if(n==cap)die("too many DAF segments");Segment*s=&a[n++];memset(s,0,sizeof*s);dafgs_c(sum);dafgn_c(255,s->id);dafus_c(sum,2,6,s->dc,s->ic);if(failed_c())die("DAF summary failed");s->begin=s->ic[4];s->end=s->ic[5];if(s->ic[3]!=2||s->end-s->begin+1<4)continue;dafgda_c(h,s->end-3,s->end,dir);if(failed_c())die("DAF directory read failed");s->init=dir[0];s->intlen=dir[1];if(!exact_int(dir[2],&s->rsize)||!exact_int(dir[3],&s->n)||s->rsize<5||(s->rsize-2)%3||s->n<1||!isfinite(s->init)||!isfinite(s->intlen)||s->intlen<=0)continue;s->degree=(s->rsize-2)/3-1;if((long double)s->n*s->rsize+4!=(long double)(s->end-s->begin+1))continue;s->valid=1;}return n; }
static Segment* segment_for(Segment*a,int n,SpiceInt target,double et){Segment*r=NULL;for(int i=0;i<n;i++){Segment*s=&a[i];if(s->valid&&s->ic[0]==target&&s->ic[2]==1&&et>=s->dc[0]&&et<=s->dc[1]){if(r)return NULL;r=s;}}return r;}
static int record_index(const Segment*s,double et){double q=(et-s->init)/s->intlen;long i=(long)floor(q);if(i<0)i=0;if(i>=s->n)i=s->n-1;return (int)i;}
static int read_record(SpiceInt h,const Segment*s,int index,double *r){SpiceInt b=s->begin+index*s->rsize;dafgda_c(h,b,b+s->rsize-1,r);return !failed_c();}
/* Direct implementation of the CSPICE documented CHBINT recurrence; no CSPICE polynomial evaluator is called. */
static void cheby(const double*c,int degree,double mid,double radius,double et,double*p,double*v){double s=(et-mid)/radius,s2=2*s,w0=0,w1=0,w2,d0=0,d1=0,d2;for(int j=degree+1;j>1;j--){w2=w1;w1=w0;w0=c[j-1]+(s2*w1-w2);d2=d1;d1=d0;d0=w1*2+(d1*s2-d2);}*p=c[0]+(s*w0-w1);*v=(w0+s*d0-d1)/radius;}
typedef struct { Segment*s; int index; double mid,radius,normalized,state[6],previous[6],next[6]; int hasPrev,hasNext; uint64_t fingerprint; } Eval;
static uint64_t fingerprint(const double*r,int n){uint64_t h=UINT64_C(1469598103934665603);for(int i=0;i<n;i++){uint64_t x=dbits(r[i]);for(int j=0;j<8;j++){h^=(unsigned char)(x>>(j*8));h*=UINT64_C(1099511628211);}}return h;}
static int eval(SpiceInt h,Segment*s,double et,Eval*out,int with_adjacent){double*r=malloc((size_t)s->rsize*sizeof*r);if(!r)die("allocation failed");out->s=s;out->index=record_index(s,et);if(!read_record(h,s,out->index,r)){free(r);return 0;}out->mid=r[0];out->radius=r[1];out->normalized=(et-r[0])/r[1];out->fingerprint=fingerprint(r,s->rsize);for(int x=0;x<3;x++)cheby(r+2+x*(s->degree+1),s->degree,r[0],r[1],et,&out->state[x],&out->state[x+3]);out->hasPrev=out->hasNext=0;if(with_adjacent&&out->index>0){double*q=malloc((size_t)s->rsize*sizeof*q);read_record(h,s,out->index-1,q);for(int x=0;x<3;x++)cheby(q+2+x*(s->degree+1),s->degree,q[0],q[1],et,&out->previous[x],&out->previous[x+3]);out->hasPrev=1;free(q);}if(with_adjacent&&out->index+1<s->n){double*q=malloc((size_t)s->rsize*sizeof*q);read_record(h,s,out->index+1,q);for(int x=0;x<3;x++)cheby(q+2+x*(s->degree+1),s->degree,q[0],q[1],et,&out->next[x],&out->next[x+3]);out->hasNext=1;free(q);}free(r);return 1;}
static int root_state(SpiceInt h,Segment*a,int n,SpiceInt object,double et,double out[6],Eval*primary){if(object==0){memset(out,0,48);return 1;}Segment*s=segment_for(a,n,object,et);if(!s)return 0;Eval e;if(!eval(h,s,et,&e,primary!=NULL))return 0;double parent[6];if(!root_state(h,a,n,s->ic[1],et,parent,NULL))return 0;for(int i=0;i<6;i++)out[i]=e.state[i]+parent[i];if(primary)*primary=e;return 1;}
static void state(FILE*f,const double*x){fputc('[',f);for(int i=0;i<6;i++)fprintf(f,"%s%.17g",i?",":"",x[i]);fputc(']',f);}static void bits(FILE*f,const double*x){fputc('[',f);for(int i=0;i<6;i++)fprintf(f,"%s\"0x%016" PRIx64 "\"",i?",":"",dbits(x[i]));fputc(']',f);}
static void emit_eval(FILE*f,const Eval*e){fprintf(f,"{\"segmentIdentity\":\"");fprintf(f,"target:%d:center:%d:frame:%d:begin:%d:end:%d",e->s->ic[0],e->s->ic[1],e->s->ic[2],e->s->begin,e->s->end);fprintf(f,"\",\"nativeSegmentId\":");jsons(f,e->s->id);fprintf(f,",\"segmentType\":2,\"recordIndex\":%d,\"recordStartEt\":%.17g,\"recordEndEt\":%.17g,\"recordStartEtBits\":\"0x%016" PRIx64 "\",\"recordEndEtBits\":\"0x%016" PRIx64 "\",\"normalizedTime\":%.17g,\"normalizedTimeBits\":\"0x%016" PRIx64 "\",\"coefficientBlockIdentity\":\"daf-word:%d:%d\",\"coefficientFingerprintFNV1a64\":\"%016" PRIx64 "\",\"positionCoefficientSpan\":[2,%d],\"velocityCoefficientSpan\":\"derivative_of_position_chebyshev\",\"evaluationRoutineIdentity\":\"project_owned_type2_chbint_recurrence_v1\",\"state\":",e->index,e->mid-e->radius,e->mid+e->radius,dbits(e->mid-e->radius),dbits(e->mid+e->radius),e->normalized,dbits(e->normalized),e->s->begin+e->index*e->s->rsize,e->s->begin+(e->index+1)*e->s->rsize-1,e->fingerprint,e->s->rsize-1);state(f,e->state);fprintf(f,",\"stateBits\":");bits(f,e->state);fprintf(f,"}");}
int main(int argc,char**argv){const char*spk=NULL,*inpath=NULL,*outpath=NULL;if(argc<2||strcmp(argv[1],"--evaluate-batch")){fprintf(stderr,"usage: --evaluate-batch --spk FILE --input-jsonl FILE --output-jsonl FILE\n");return 2;}for(int i=2;i<argc;i++){if(i+1<argc&&!strcmp(argv[i],"--spk"))spk=argv[++i];else if(i+1<argc&&!strcmp(argv[i],"--input-jsonl"))inpath=argv[++i];else if(i+1<argc&&!strcmp(argv[i],"--output-jsonl"))outpath=argv[++i];}if(!spk||!inpath||!outpath)die("missing required argument");SpiceInt h;dafopr_c(spk,&h);if(failed_c())die("DAF open failed");Segment seg[64];int n=load(h,seg,64);FILE*in=fopen(inpath,"rb"),*out=fopen(outpath,"wb");if(!in||!out)die("input/output open failed");char line[4096],id[512];int bad=0;while(fgets(line,sizeof line,in)){SpiceInt target,center;double et,decimal;uint64_t eb;memset(&et,0,8);if(!strfield(line,"sampleId",id,sizeof id)||!intfield(line,"targetId",&target)||!intfield(line,"centerId",&center)||!numfield(line,"queryEt",&decimal)||!hexfield(line,"queryEtHex",&eb)){bad=1;continue;}memcpy(&et,&eb,8);if(dbits(decimal)!=eb){fprintf(stderr,"queryEt/queryEtHex mismatch for %s\n",id);bad=1;continue;}double tr[6],cr[6],final[6];Eval p;if(!root_state(h,seg,n,target,et,tr,&p)||!root_state(h,seg,n,center,et,cr,NULL)){fprintf(stderr,"unsupported or ambiguous center chain for %s\n",id);bad=1;continue;}for(int k=0;k<6;k++)final[k]=tr[k]-cr[k];int adjacent=(p.hasPrev||p.hasNext)&&((dbits(et)==dbits(p.mid-p.radius))||(dbits(et)==dbits(p.mid+p.radius))||ordered(et)+1==ordered(p.mid-p.radius)||ordered(p.mid-p.radius)+1==ordered(et)||ordered(et)+1==ordered(p.mid+p.radius)||ordered(p.mid+p.radius)+1==ordered(et));fprintf(out,"{\"schemaVersion\":1,\"recordType\":\"de405_project_owned_spk_record_probe\",\"sampleId\":");jsons(out,id);fprintf(out,",\"target\":%d,\"center\":%d,\"queryEt\":%.17g,\"queryEtBits\":\"0x%016" PRIx64 "\",\"queryEtHex\":\"0x%016" PRIx64 "\",\"selectionMethod\":\"project_owned_type2_directory_floor_half_open_last_closed_v1\",\"selectionObservable\":false,\"unavailableReason\":\"api_does_not_expose_selected_record\",\"projectSelectedRecord\":",target,center,et,eb,eb);emit_eval(out,&p);fprintf(out,",\"adjacentRecordEvaluations\":[");if(adjacent&&p.hasPrev){state(out,p.previous); }fprintf(out,"] ,\"projectStateKmKmPerSec\":");state(out,final);fprintf(out,",\"projectStateBits\":");bits(out,final);fprintf(out,"}\n");}fclose(in);fclose(out);dafcls_c(h);return bad?1:0;}
